### ISSUE TITLE
Missing Positional Requirements

### ISSUE THREAD

**Issue by ronalddas** [naver/sqlova#11]
When I run `python3 train.py --seed 1 --bS 16 --accumulate_gradients 2 --bert_type_abb uS --fine_tune --lr 0.001 --lr_bert 0.00001 --max_seq_leng 222` .
I get the error
`
Traceback (most recent call last):
  File "train.py", line 582, in <module>
    model, model_bert, tokenizer, bert_config = get_models(args, BERT_PT_PATH, trained=True, path_model_bert=path_model_bert, path_model=path_model)
  File "train.py", line 156, in get_models
    args.no_pretraining)
  File "train.py", line 120, in get_bert
    model_bert = BertModel(bert_config)
TypeError: __init__() missing 2 required positional arguments: 'is_training' and 'input_ids
`
I am using Python 3.6.7

**Comment by whwang299** [comment]
Hi @ronalddas 

Hm.. BertModel class does not take `is_training` and `input_ids` as arguments (see below)

**Comment by ronalddas** [comment]
I had pre-trained-bert installed, it was calling the BertModel class from there.
