### ISSUE TITLE
what does table-aware mean?

### ISSUE THREAD

**Issue by guotong1988** [naver/sqlova#16]
It is basic but I still don't know.

@whwang299 
Thank you very much!

**Comment by whwang299** [comment]
During question encoding stage, the headers from corresponding tables are used. Thus, it is called 'table-aware'.

Wonseok

**Comment by guotong1988** [comment]
HOW the headers is used for question?

**Comment by guotong1988** [comment]
Could you please show me the code for table-aware? Thank you! @whwang299

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/57346078-d16ede00-717f-11e9-812e-f1a921f3212f.png)

Headers info do not pass into the `encode` methods??

**Comment by guotong1988** [comment]
Oh, table-aware means in BERT layer, the headers info and question info are both input.
![image](https://user-images.githubusercontent.com/4702353/57346609-c1f09480-7181-11e9-93d0-aa59368de165.png)
