### ISSUE TITLE
can not understand here in paper.

### ISSUE THREAD

**Issue by guotong1988** [naver/sqlova#17]
![image](https://user-images.githubusercontent.com/4702353/57204050-96d23d80-6fe7-11e9-837b-c08f31a19a25.png)

`H` is the table header and `col` is what?

**Comment by guotong1988** [comment]
Oh... `H` is the question hidden states

**Comment by whwang299** [comment]
@guotong1988 
Yes. `H` stands for the hidden vector from final layer of BERT.

**Comment by guotong1988** [comment]
Thank you! What is `col`?

**Comment by guotong1988** [comment]
Could you give an example for `col`?

**Comment by whwang299** [comment]
`col1` indicates the header of the table. For example, if table headers are ['A', 'B', 'C'], there are three columns and `col1` indicates 'A'.
