### ISSUE TITLE
What is the function of `train_shallow_layer.py` and `train_decoder_layer.py`?

### ISSUE THREAD

**Issue by guotong1988** [naver/sqlova#27]
It seems `train.py` works.
Why need `train_shallow_layer.py` and `train_decoder_layer.py`?
Thank you.

**Comment by whwang299** [comment]
There scripts are for training other models (Shallow Layer & Decoder Layer).
For the detail, please refer to the [technical report](https://ssl.pstatic.net/static/clova/service/clova_ai/research/publications/SQLova.pdf).

Wonseok
