### ISSUE TITLE
Why wnp’s result is not the input for wcp?

### ISSUE THREAD

**Issue by guotong1988** [naver/sqlova#28]
![image](https://user-images.githubusercontent.com/4702353/59270891-245b1a00-8c85-11e9-94aa-bd20af31b3ed.png)
In https://github.com/naver/sqlova/blob/master/sqlova/model/nl2sql/wikisql_models.py

`wnp` is the where number predict, `wcp` is the where column predict.
So I think `wnp`'s result should be the input for `wcp`.
Thank you! @whwang299

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/59317839-3a092780-8cf7-11e9-8774-faa5a8dc6c8c.png)

**Comment by whwang299** [comment]
Hi @guotong1988 
The WCP module in SQLova estimates the probability of generating each column in where clause. And select top `n` number of column among them where `n` is estimated from the WNP module.

Wonseok
