### ISSUE TITLE
Annotated queries not lower-cased

### ISSUE THREAD

**Issue by vincentlux** [naver/sqlova#6]
Hi, may I ask if all the queries are supposed to be lowercased during the annotation? Since in your code, for the bert, uS is the default setting. However, when annotating queries, they are not being [[lowercased.]](https://github.com/naver/sqlova/blob/b7ce9ad421fd4688ef8592f93b248df85e9995ad/annotate_ws.py#L188) 

Thank you very much for the help!

**Comment by whwang299** [comment]
Hi @vincentlux 

Not necessarily. The questions are lower-cased (if they haven't) at here depending on BERT models.

https://github.com/naver/sqlova/blob/b7ce9ad421fd4688ef8592f93b248df85e9995ad/sqlova/utils/utils_wikisql.py#L591

As for BERT-cased models, I performed some experiments with them but found uncased models are better at least with the conditions I tried.

Thanks!

Wonseok

**Comment by vincentlux** [comment]
Hi @whwang299 

Thank you for your quick response! That makes sense.  I really appreciate your help 👍 

Vincent
